# 使用するポート番号
server:
  port: 8081

# DB接続情報
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres

# Eurekaの情報
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
